### PR TITLE
refactor: ts simplification

### PR DESCRIPTION
**Pull request by NathanWalker**
@NathanaelA @bradmartin This is another example of how simple TS can be with these plugins.

@TheOriginalJosh this reduces a lot of unnecessary overhead and still works exactly the same.

### CODE REVIEW

**Comment by JoshDSommer** [comment]
Cool, I didn't know you didn't need the android and ios files. couldn't we potentially just get rid of the common.ts file and leave it in just one file, nativescript-parallax.ts or is common.ts required?

**Comment by NathanaelA** [comment]
No, common is not needed unless you want it.  I think only one of my plugins actually has a common file; the rest everything is implemented in the .android.js or .ios.js files.

**Comment by NathanWalker** [comment]
When you publish this later, lemme know and I'd like to look at some other things here.

**Comment by NathanWalker** [comment]
You could leave it in 1 file definitely. However, hold off on that until we can look at the publish later.

**Pull request merged**
